// flow-typed signature: c75b8122d00db69a2e7cb50c73a24682
// flow-typed version: <<STUB>>/babel-eslint_v^7.2.3/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
