// flow-typed signature: d2827a88cf0a621fd036b63b053ddcd5
// flow-typed version: <<STUB>>/@tuomashatakka/eslint-config_v^0.1.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tuomashatakka/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tuomashatakka/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@tuomashatakka/eslint-config/index' {
  declare module.exports: $Exports<'@tuomashatakka/eslint-config'>;
}
declare module '@tuomashatakka/eslint-config/index.js' {
  declare module.exports: $Exports<'@tuomashatakka/eslint-config'>;
}
